# Generated by Django 4.0 on 2025-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWallApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='theWallApp.User'),
        ),
    ]
